# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/annotate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Annotation(object):
    def setupUi(self, Annotation):
        Annotation.setObjectName("Annotation")
        Annotation.resize(1440, 847)
        self.horizontalSlider = QtWidgets.QSlider(Annotation)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 540, 581, 25))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton = QtWidgets.QPushButton(Annotation)
        self.pushButton.setGeometry(QtCore.QRect(30, 570, 100, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Annotation)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 570, 100, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Annotation)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 570, 100, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Annotation)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 570, 100, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Annotation)
        self.label.setGeometry(QtCore.QRect(30, 545, 58, 21))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalSlider_2 = QtWidgets.QSlider(Annotation)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(490, 620, 171, 25))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(Annotation)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(130, 620, 291, 25))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_2 = QtWidgets.QLabel(Annotation)
        self.label_2.setGeometry(QtCore.QRect(440, 620, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Annotation)
        self.label_3.setGeometry(QtCore.QRect(30, 620, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Annotation)
        self.label_4.setGeometry(QtCore.QRect(30, 650, 651, 151))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(Annotation)
        self.pushButton_5.setGeometry(QtCore.QRect(1150, 730, 101, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Annotation)
        self.pushButton_6.setGeometry(QtCore.QRect(890, 730, 111, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.home_button_annotator = QtWidgets.QPushButton(Annotation)
        self.home_button_annotator.setGeometry(QtCore.QRect(1030, 730, 101, 51))
        self.home_button_annotator.setObjectName("home_button_annotator")
        self.pushButton_8 = QtWidgets.QPushButton(Annotation)
        self.pushButton_8.setGeometry(QtCore.QRect(890, 670, 111, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Annotation)
        self.pushButton_9.setGeometry(QtCore.QRect(760, 730, 111, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Annotation)
        self.pushButton_10.setGeometry(QtCore.QRect(760, 670, 111, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_5 = QtWidgets.QLabel(Annotation)
        self.label_5.setGeometry(QtCore.QRect(1030, 690, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Annotation)
        QtCore.QMetaObject.connectSlotsByName(Annotation)

    def retranslateUi(self, Annotation):
        _translate = QtCore.QCoreApplication.translate
        Annotation.setWindowTitle(_translate("Annotation", "Annotation Screen"))
        self.pushButton.setText(_translate("Annotation", "Play from Start"))
        self.pushButton_2.setText(_translate("Annotation", "Backward"))
        self.pushButton_3.setText(_translate("Annotation", "Play/Pause"))
        self.pushButton_4.setText(_translate("Annotation", "Forward"))
        self.label.setText(_translate("Annotation", "Time:"))
        self.label_2.setText(_translate("Annotation", "Volume:"))
        self.label_3.setText(_translate("Annotation", "Current Speed:"))
        self.label_4.setText(_translate("Annotation", "Annotation Instructions:\n"
"To annotate, first click select file and select the media to annotate, then select play.\n"
"There will be five second delay for the annotator to move to the starting position\n"
"before annotation  and the media starts. The \'p\' key can also be pressed to play and\n"
"pause media. The forward and backward buttons will move the media by five seconds \n"
"in their respective directions."))
        self.pushButton_5.setText(_translate("Annotation", "Clear"))
        self.pushButton_6.setText(_translate("Annotation", "Save as CSV"))
        self.home_button_annotator.setText(_translate("Annotation", "Main Menu"))
        self.pushButton_8.setText(_translate("Annotation", "Play"))
        self.pushButton_9.setText(_translate("Annotation", "Save as PNG"))
        self.pushButton_10.setText(_translate("Annotation", "Select File"))
        self.label_5.setText(_translate("Annotation", "Point:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Annotation = QtWidgets.QWidget()
    ui = Ui_Annotation()
    ui.setupUi(Annotation)
    Annotation.show()
    sys.exit(app.exec_())
