# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/audio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_liveAudio(object):
    def setupUi(self, liveAudio):
        liveAudio.setObjectName("liveAudio")
        liveAudio.resize(1440, 847)
        self.frame = QtWidgets.QFrame(liveAudio)
        self.frame.setGeometry(QtCore.QRect(360, 530, 721, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 30, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 90, 111, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(30, 120, 251, 32))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 111, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(160, 170, 111, 21))
        self.textEdit.setObjectName("textEdit")
        self.graphicsView = PlotWidget(liveAudio)
        self.graphicsView.setGeometry(QtCore.QRect(260, 90, 901, 321))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(liveAudio)
        QtCore.QMetaObject.connectSlotsByName(liveAudio)

    def retranslateUi(self, liveAudio):
        _translate = QtCore.QCoreApplication.translate
        liveAudio.setWindowTitle(_translate("liveAudio", "LiveAudio"))
        self.pushButton.setText(_translate("liveAudio", "Start"))
        self.pushButton_2.setText(_translate("liveAudio", "Stop"))
        self.label.setText(_translate("liveAudio", "Data Source:"))
        self.label_2.setText(_translate("liveAudio", "Spectogram Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    liveAudio = QtWidgets.QWidget()
    ui = Ui_liveAudio()
    ui.setupUi(liveAudio)
    liveAudio.show()
    sys.exit(app.exec_())
